services:
  frontend:
    image: docker.grug.dev/licensepanel:latest
    container_name: panel
    env_file:
      - frontend.env
    depends_on:
      - mongo
    ports:
      - 3000:3000
    networks:
      - license

  panel-api:
    image: docker.grug.dev/licenseapi:latest
    container_name: panel-api
    env_file: 
      - backend.env
    depends_on:
      - mongo
    ports:
      - 3001:3001
    environment:
      - MONGODB_URI=mongodb://root:TestDB@mongo
      - MONGODB_DB=panel
    networks:
      - license

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - license

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: TestDB
    networks:
      - license

  injector:
    image: docker.grug.dev/injector:latest
    volumes:
      - './injector/cache:/app/cache'
      - './injector/software:/app/software'
    networks:
      - license

networks:
  license:
    name: license
